# Site settings
title: Hash Cookies | Web design and software services
email: milind@hashcooki.es
description: "Beautiful responsive web designs created professionally at competitive prices."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hashcooki.es"
twitter_username: goobimama
github_username:  milindalvares

# Build settings
markdown: kramdown

repository: https://github.com/milindalvares/hash-cookies/

permalink: /journal/:title


gems:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
    style: compressed


webrick:
  headers:
     Cache-Control: max-age=608400