# Site settings
title: Hash Cookies | Web design and software services
email: milind@hashcooki.es
description: "Beautiful responsive web designs created professionally at competitive prices." 
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: goobimama
github_username:  milindalvares
thumbnail: http://hashcooki.es/assets/images/hc-thumbnail.png

# Build settings
markdown: kramdown

repository: https://github.com/milindalvares/hash-cookies/

permalink: /journal/:title