# Site settings
title: Hash Cookies
email: milind@hashcooki.es
description: > # this means to ignore newlines until "baseurl:"
 A design driven agency specialising in building web products. 
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: goobimama
github_username:  milindalvares

# Build settings
markdown: kramdown

repository: https://github.com/milindalvares/hash-cookies/

